FROM gocd/gocd-agent-debian-11:v23.1.0

ENV MAVEN_VERSION 3.8.8
ENV DEBIAN_FRONTEND=noninteractive

USER root

# Base packages
RUN apt-get update && \
  apt-get install -y --no-install-recommends \
  wget \
  curl \
  ca-certificates \
  python3 \
  python3-pip \
  python3-venv \
  gnupg2 \
  binutils \
  libc6-dev \
  libcurl4 \
  libedit2 \
  libgcc-9-dev \
  libpython2.7 \
  libsqlite3-0 \
  libstdc++-9-dev \
  libxml2 \
  libz3-dev \
  pkg-config \
  tzdata \
  zlib1g-dev \
  make \
  lsb-base \
  lsb-release \
  && rm -rf /var/lib/apt/lists/*

# Microsoft package signing key
RUN wget https://packages.microsoft.com/config/debian/11/packages-microsoft-prod.deb -O packages-microsoft-prod.deb && \
  dpkg -i packages-microsoft-prod.deb && \
  rm packages-microsoft-prod.deb

# nodesource PPA
RUN curl -sL https://deb.nodesource.com/setup_16.x  | bash -

# php repo
RUN echo "deb https://packages.sury.org/php/ $(lsb_release -sc) main" | tee /etc/apt/sources.list.d/sury-php.list
RUN wget -qO - https://packages.sury.org/php/apt.gpg | apt-key add -

# SDKs and Runtimes
RUN apt-get update && \
  apt-get install -y --no-install-recommends \
  openjdk-17-jdk \
  openjdk-17-jre \
  dotnet-sdk-6.0 \
  nodejs \
  php8.2 \
  php8.2-cli \
  php8.2-common \
  && rm -rf /var/lib/apt/lists/*

# Install Maven
RUN curl -fsSL https://downloads.apache.org/maven/maven-3/$MAVEN_VERSION/binaries/apache-maven-$MAVEN_VERSION-bin.tar.gz | tar xzf - -C /usr/share \
  && mv /usr/share/apache-maven-$MAVEN_VERSION /usr/share/maven \
  && ln -s /usr/share/maven/bin/mvn /usr/bin/mvn

# swift
RUN wget https://download.swift.org/swift-5.8-release/ubuntu2004/swift-5.8-RELEASE/swift-5.8-RELEASE-ubuntu20.04.tar.gz \
    && tar -xvzf swift-5.8-RELEASE-ubuntu20.04.tar.gz \
    && mv swift-5.8-RELEASE-ubuntu20.04 /opt/swift \
    && rm -rf swift-5.8* \
    && wget -q -O - https://swift.org/keys/all-keys.asc | gpg --import - \
    && echo "export PATH=/opt/swift/usr/bin:$PATH" >> ~/.bashrc

# Install Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

ENV MAVEN_HOME /usr/share/maven
