FROM gocd/gocd-agent-debian-11:v23.1.0

ENV MAVEN_VERSION 3.8.8
ENV DEBIAN_FRONTEND=noninteractive

USER root

# Base packages
RUN apt-get update && \
  apt-get install -y --no-install-recommends \
  wget \
  curl \
  gnupg \
  ca-certificates \
  python3 \
  python3-pip \
  python3-venv \
  make \
  && rm -rf /var/lib/apt/lists/*

# Microsoft package signing key
RUN wget https://packages.microsoft.com/config/debian/11/packages-microsoft-prod.deb -O packages-microsoft-prod.deb && \
  dpkg -i packages-microsoft-prod.deb && \
  rm packages-microsoft-prod.deb

# nodesource PPA
RUN curl -sL https://deb.nodesource.com/setup_16.x  | bash

# SDKs and Runtimes
RUN apt-get update && \
  apt-get install -y --no-install-recommends \
  openjdk-17-jdk \
  openjdk-17-jre \
  dotnet-sdk-6.0 \
  nodejs \
  && rm -rf /var/lib/apt/lists/*

# Install Maven
RUN curl -fsSL https://downloads.apache.org/maven/maven-3/$MAVEN_VERSION/binaries/apache-maven-$MAVEN_VERSION-bin.tar.gz | tar xzf - -C /usr/share \
  && mv /usr/share/apache-maven-$MAVEN_VERSION /usr/share/maven \
  && ln -s /usr/share/maven/bin/mvn /usr/bin/mvn

ENV MAVEN_HOME /usr/share/maven
