FROM gocd/gocd-agent-debian-11:v23.1.0

ENV DEBIAN_FRONTEND=noninteractive

USER root

# Base packages
RUN apt-get update && \
  apt-get install -y --no-install-recommends \
  wget \
  ca-certificates \
  && rm -rf /var/lib/apt/lists/*

# Microsoft package signing key
RUN wget https://packages.microsoft.com/config/debian/11/packages-microsoft-prod.deb -O packages-microsoft-prod.deb && \
  dpkg -i packages-microsoft-prod.deb && \
  rm packages-microsoft-prod.deb

# SDKs and Runtimes
RUN apt-get update && \
  apt-get install -y --no-install-recommends \
  dotnet-sdk-6.0 \
  && rm -rf /var/lib/apt/lists/*
