FROM gocd/gocd-agent-debian-11:v23.1.0

ENV MAVEN_VERSION 3.8.8
ENV DEBIAN_FRONTEND=noninteractive

USER root

RUN apt-get update && \
  apt-get install -y --no-install-recommends \
  openjdk-17-jdk openjdk-17-jre \
  && rm -rf /var/lib/apt/lists/*

RUN curl -fsSL https://downloads.apache.org/maven/maven-3/$MAVEN_VERSION/binaries/apache-maven-$MAVEN_VERSION-bin.tar.gz | tar xzf - -C /usr/share \
  && mv /usr/share/apache-maven-$MAVEN_VERSION /usr/share/maven \
  && ln -s /usr/share/maven/bin/mvn /usr/bin/mvn

ENV MAVEN_HOME /usr/share/maven
